POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "{choices{id, questionId, state, evolution}}"
}

###

POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "{choicesByQuestion(questionId: 1) {state, evolution}}"
}

###

POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "mutation{saveChoice(questionId: 1, state: \"MEDIUM\", evolution: \"BETTER\"){id, questionId, state, evolution}}"
}

###