CREATE TABLE IF NOT EXISTS public.choice(
    id           LONG NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    question_id  LONG NOT NULL,
    state        VARCHAR(10) NOT NULL,
    evolution    VARCHAR(10) NOT NULL,
    PRIMARY KEY (id)
);